FROM golang:1.25.4-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o worker ./cmd/worker

# Final Stage
FROM alpine:latest
# INSTALL FFMPEG HERE
RUN apk add --no-cache ffmpeg
WORKDIR /root/
COPY --from=builder /app/worker .
CMD ["./worker"]
