FROM golang:1.25.4-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o worker ./cmd/worker

FROM linuxserver/ffmpeg:version-8.0-cli AS ffmpeg

# Final Stage
FROM alpine:latest
# Install ffmpeg
RUN apk add --no-cache ffmpeg
WORKDIR /root/
COPY --from=builder /app/worker .
COPY --from=ffmpeg /usr/local/bin/ffmpeg /usr/local/bin/ffmpeg
RUN apk add --no-cache libstdc++ libgomp expat
CMD ["./worker"]
